---
title: "Metworx v 3.0.2-r2 software listing"
output: github_document
---


```{r setup, include=FALSE}
dir.create("lib")
.libPaths("lib")
knitr::opts_chunk$set(echo = FALSE)
```



```{r install-packages, message=FALSE}
if(!require("tibble")) install.packages("tibble")
if(!require("jsonlite")) install.packages("jsonlite")
if(!require("stringr")) install.packages("stringr")
if(!require("dplyr")) install.packages("dplyr")
```

```{r load-libraries, message=FALSE}
library(jsonlite)
library(stringr)
library(dplyr)
library(tibble)
library(knitr)
```


```{r}
metworxv <- "3.0.2-r2"
ami <- tribble(
  ~Region,       ~`Intel12 AMI`,  ~`Intel14 AMI`,
  "us-west-2",    "ami-f543fc8d", "ami-9f45fae7",
  "us-east-1",    "ami-b8a39bc2", "ami-faa19980",
  "eu-central-1", "ami-5dab3032", "ami-d5b42fba"
)
```

```{r get-versions, message=FALSE, warning=FALSE}
## Operating system

ubuntuv <- system("lsb_release -a", intern=TRUE)
ubuntuv_table <- str_split(grep("^Release",ubuntuv,value=T),"\t",simplify=T)
ubuntuv_table[,1] <- "Ubuntu (OS)"


## R

rv <- system("R --version", intern=TRUE)
rv_table <- c(
  "R",
  stringr::str_extract(rv[1],"[[:digit:]][\\.][[:digit:]][\\.][[:digit:]]")
)
                          

## Rstudio-server and rstudio deskop

rstudiov <- system("rstudio-server version", intern=TRUE)
rstudiov_table <- c("Rstudio-server/desktop", rstudiov)

## PiranaJS

piranajsv <- fromJSON("/opt/pirana/piranajs/current/package.json")$version
piranajsv_table <- c("PiranaJS", piranajsv)


## Pirana Desktop

piranav <- readLines("/opt/pirana/pirana/pirana.pl")
piranav <- piranav[grep("our \\$version|our \\$pirana_build", piranav)]
piranav <- str_extract(piranav, c("[[:digit:]]+.[[:digit:]]+.[[:digit:]]+", "[[:digit:]]+"))
piranav <- paste(c("Version:", "Build:"), piranav)
piranav_table <- c("Pirana", paste(piranav,collapse=","))


## gFortran

gfv <- system("gfortran --version", intern=TRUE)[1]
gfv_table <- 
  c("GNU Fortran",str_extract(gfv,"\\d*\\.\\d*\\.\\d*\\s\\d*")
    )
gfv_table <- gfv_table[gfv_table!=""]


## IntelFortran

ifv <- system2("ifort", "-v", stderr=TRUE)
ifv_table <- c("Intel Fortran",ifv)

## OpenBUGS

# openbugsv <- system("OpenBUGS", intern=TRUE)
openbugsv <- "OpenBUGS version 3.2.3 rev 1012"
openbugsv_table <- c("OpenBUGS", "v 3.2.3 r 1012")

## Stan

stanv <- installed.packages()["rstan","Version"]
stanv_table <- c("Stan", stanv)

## Python

pythonv <- system2("python","--version", stderr=TRUE)
pythonv_table <- str_split(pythonv," ",simplify=TRUE)

## PsN

psnv <- system("which execute | xargs ls -l", intern=TRUE)
psnv <- str_extract(psnv, "[[:digit:]].[[:digit:]].[[:digit:]]")
psnv_table <- c("Perl speaks NONMEM", psnv)


## NONMEM

nmv <- list.dirs("/opt/NONMEM", recursive=FALSE)
nmv_table <- c("NONMEM", "7.2, 7.3, 7.4")

## Grid Engine

gev <- system("qstat -help", intern=TRUE)[1]
gev_table <- str_split(gev," ",simplify=TRUE)

## TexLive

latexv <- system("pdflatex -v", intern=TRUE)[1]
latexv_table <- c("TexLive (LaTex)", str_split(latexv," ", simplify=TRUE)[2])

## Subversion

svnv <- system("svn help", intern=TRUE)[2]
svnv_table <- 
  c("Subversion", str_extract(svnv,"[[:digit:]].[[:digit:]].[[:digit:]]"))

## Shiny pro

shinyv <- system("shiny-server", intern=TRUE)[1]
shinyv <- str_extract(shinyv, "v[[:digit:]].[[:digit:]].[[:digit:]].[[:digit:]]*")
shinyv_table <- c("Shiny server pro",shinyv)

## SAS

sasv <- basename(list.dirs("/usr/local/SASHome/SASFoundation/", recursive=F))
sasv_table <- c("SAS", sasv)

## Monolix

monolixv <- basename(list.dirs("/opt/monolix", recursive=FALSE))
monolixv <- monolixv[grep("onolix", monolixv)]
monolixv_table <- c(str_extract(monolixv, "\\D+"),
                    str_extract(monolixv,"\\d+\\D\\d*"))

## Matlab

matlabv <- system("which matlab | xargs ls -al", intern=TRUE)
matlabv <- str_extract(matlabv, "R[[:digit:]]+[[:alnum:]]*")
matlabv_table <- c("Matlab", matlabv)


## Git
gitv <- system("git --version", intern=TRUE)
gitv_table <- c("Git", 
  str_extract(gitv,"[[:digit:]]+\\.[[:digit:]]+\\.[[:digit:]]+")
  )
```


```{r ami}
ami %>% kable
```


```{r table}
versions <- lapply(grep("_table$",ls(),value=TRUE),get)
tab <- do.call(rbind, versions)
kable(tab, col.names=c("Software","Version"))
```

